remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: [Slim Karkar]
description: [repos for teaching projects]
show_downloads: ["false"]
