remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
show_downloads: [false]
title: [Slim Karkar]
description: [repos for teaching projects]

